language: rust

rust:
  - stable
  - beta

env:
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES=''
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='generic-impls'

matrix:
  include:
    # Also run the default tests on nightly.
    - rust: nightly
      env: TEST_COMMAND=test EXTRA_FLAGS='' FEATURES=''
    - rust: nightly
      env: TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='generic-impls'
    # Run benchmarks only on nightly.
    - rust: nightly
      env: TEST_COMMAND=bench EXTRA_FLAGS='' FEATURES='bench'
    # Test no-std only on nightly.
    - rust: nightly
      env: TEST_COMMAND=build EXTRA_FLAGS=--no-default-features FEATURES=''

script:
  - cargo $TEST_COMMAND --features="$FEATURES" $EXTRA_FLAGS

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots
