[package]
name = "subtle"
version = "0.6.3"
authors = ["Isis Lovecruft <isis@patternsinthevoid.net>",
           "Henry de Valence <hdevalence@hdevalence.ca>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/dalek-cryptography/subtle"
homepage = "https://dalek.rs/"
documentation = "https://docs.rs/subtle"
categories = ["cryptography", "no-std"]
keywords = ["cryptography", "constant-time", "utilities"]
description = "Pure-Rust traits and utilities for constant-time cryptographic implementations."
exclude = [
    "**/.gitignore",
    ".travis.yml",
]

[badges]
travis-ci = { repository = "dalek-cryptography/subtle", branch = "master"}

[features]
default = ["std", "generic-impls"]
std = []
bench = []
nightly = []
# Enables generic implementations of ConditionallyNegatable and ConditionallySwappable
generic-impls = []
